import { TestScoreResponseType } from "./types";

export const aGrowth: TestScoreResponseType[] = [
  {
    assessmentId: 80693,
    classesScores: [
      {
        classId: 60392,
        assessmentId: 80692,
        className: "Class SM",
        teacher: {
          userId: 758124,
          userName: null,
          password: null,
          title: null,
          firstName: "Dat",
          middleName: "",
          lastName: "Tch",
          email: null,
          schoolId: null,
          school: null,
          districtId: null,
          district: null,
          roleId: null,
          role: null,
          status: null,
          statusType: null,
          gradeId: null,
          grade: null,
          gradeEs: null,
          studentId: null,
          learningStyleId: null,
          learningStyle: null,
          createdBy: null,
          modifiedBy: null,
          createdDate: null,
          modifiedDate: null,
          termsAcceptedStatus: null,
          termsVersionAccepted: null,
          termsAcceptedDate: null,
          stateId: null,
          assignable: false,
          numAssign: 0,
          phone: null,
          userLicenses: null,
          className: null,
          classId: null,
          activationCode: null,
          activationExpiredDate: null,
          activationStatus: null,
          authorized: null,
          authorizedBy: null,
          authorizedDate: null,
          hasParent: false,
          lmsId: null,
          instructorRole: null,
          avatar: null,
          avatarSetting: null,
          languageId: null,
          spokenLanguage: null,
          classCode: null,
          parentNum: null,
          salesManager: null,
          linked: null,
          selected: null,
          opt: null,
          optCiu: null,
          optUpdateStatus: null,
          googleClassroomId: null,
          googleRefreshToken: null,
          fullName: "Dat Tch",
          numOfAssignments: null,
          accessCode: null,
          canvasRefreshToken: null,
          importFromCanvas: false,
          canvasImportOption: null,
          studentAssignmentStatus: null,
          cleverId: null,
          emailNotification: null,
          schoologyOauthKey: null,
          schoologyId: null,
          schoologyEnrollmentId: null,
          userDeviceDTOS: null,
          mapStatus: {},
          lockAssignmentTemp: false,
          assignedByTeacher: false,
          allowImpersonation: false,
          classNum: null,
          classNames: null,
          camelFirstLastName: "Dat Tch",
          searchSchoolUser: false,
          resendTeacherVerification: false,
          shownHelp: null,
          needTermAccepted: false,
          allowImpersonated: false,
          firstLastName: "Dat Tch",
          lastFirstName: "Tch, Dat",
          displayName: "Dat Tch",
        },
        score: 5,
        domainScores: [
          {
            domainId: 21,
            displayOrder: 2,
            domainName: "Operations & Algebraic Thinking",
            domainCode: "OA",
            domainColorCode: "#E4412B",
            percentageScore: 0,
            proficiencyLevel: "Below Proficient",
            fillColor: "#E4412B",
            strokeColor: "#808285",
            limitDomain: false,
          },
          {
            domainId: 19,
            displayOrder: 4,
            domainName: "Number And Operations-Fractions",
            domainCode: "NF",
            domainColorCode: "#EF7C32",
            percentageScore: 16,
            proficiencyLevel: "Below Proficient",
            fillColor: "#EF7C32",
            strokeColor: "#808285",
            limitDomain: false,
          },
          {
            domainId: 16,
            displayOrder: 5,
            domainName: "Measurement And Data",
            domainCode: "MD",
            domainColorCode: "#F3CE69",
            percentageScore: 0,
            proficiencyLevel: "Below Proficient",
            fillColor: "#F3CE69",
            strokeColor: "#808285",
            limitDomain: false,
          },
        ],
        studentScores: [
          {
            studentId: 758132,
            displayName: "Stu SM",
            firstName: "Stu",
            lastName: "SM",
            proficiencyLevel: "Below Proficient",
            score: 7,
            fillColor: "#ED7092",
            strokeColor: "#ED7092",
            domainScores: [
              {
                domainId: 21,
                displayOrder: 2,
                domainName: "Operations & Algebraic Thinking",
                domainCode: "OA",
                domainColorCode: "#E4412B",
                percentageScore: 0,
                proficiencyLevel: "Below Proficient",
                fillColor: "#E4412B",
                strokeColor: "#808285",
                limitDomain: false,
              },
              {
                domainId: 19,
                displayOrder: 4,
                domainName: "Number And Operations-Fractions",
                domainCode: "NF",
                domainColorCode: "#EF7C32",
                percentageScore: 16,
                proficiencyLevel: "Below Proficient",
                fillColor: "#EF7C32",
                strokeColor: "#808285",
                limitDomain: false,
              },
              {
                domainId: 16,
                displayOrder: 5,
                domainName: "Measurement And Data",
                domainCode: "MD",
                domainColorCode: "#F3CE69",
                percentageScore: 0,
                proficiencyLevel: "Below Proficient",
                fillColor: "#F3CE69",
                strokeColor: "#808285",
                limitDomain: false,
              },
            ],
          },
        ],
      },
      {
        classId: 60386,
        assessmentId: 80692,
        className: "Class_1",
        teacher: {
          userId: 758124,
          userName: null,
          password: null,
          title: null,
          firstName: "Dat",
          middleName: "",
          lastName: "Tch",
          email: null,
          schoolId: null,
          school: null,
          districtId: null,
          district: null,
          roleId: null,
          role: null,
          status: null,
          statusType: null,
          gradeId: null,
          grade: null,
          gradeEs: null,
          studentId: null,
          learningStyleId: null,
          learningStyle: null,
          createdBy: null,
          modifiedBy: null,
          createdDate: null,
          modifiedDate: null,
          termsAcceptedStatus: null,
          termsVersionAccepted: null,
          termsAcceptedDate: null,
          stateId: null,
          assignable: false,
          numAssign: 0,
          phone: null,
          userLicenses: null,
          className: null,
          classId: null,
          activationCode: null,
          activationExpiredDate: null,
          activationStatus: null,
          authorized: null,
          authorizedBy: null,
          authorizedDate: null,
          hasParent: false,
          lmsId: null,
          instructorRole: null,
          avatar: null,
          avatarSetting: null,
          languageId: null,
          spokenLanguage: null,
          classCode: null,
          parentNum: null,
          salesManager: null,
          linked: null,
          selected: null,
          opt: null,
          optCiu: null,
          optUpdateStatus: null,
          googleClassroomId: null,
          googleRefreshToken: null,
          fullName: "Dat Tch",
          numOfAssignments: null,
          accessCode: null,
          canvasRefreshToken: null,
          importFromCanvas: false,
          canvasImportOption: null,
          studentAssignmentStatus: null,
          cleverId: null,
          emailNotification: null,
          schoologyOauthKey: null,
          schoologyId: null,
          schoologyEnrollmentId: null,
          userDeviceDTOS: null,
          mapStatus: {},
          lockAssignmentTemp: false,
          assignedByTeacher: false,
          allowImpersonation: false,
          classNum: null,
          classNames: null,
          camelFirstLastName: "Dat Tch",
          searchSchoolUser: false,
          resendTeacherVerification: false,
          shownHelp: null,
          needTermAccepted: false,
          allowImpersonated: false,
          firstLastName: "Dat Tch",
          lastFirstName: "Tch, Dat",
          displayName: "Dat Tch",
        },
        score: 43,
        domainScores: [
          {
            domainId: 21,
            displayOrder: 2,
            domainName: "Operations & Algebraic Thinking",
            domainCode: "OA",
            domainColorCode: "#E4412B",
            percentageScore: 43,
            proficiencyLevel: "Proficient",
            fillColor: "#E4412B",
            strokeColor: "#808285",
            limitDomain: false,
          },
          {
            domainId: 19,
            displayOrder: 4,
            domainName: "Number And Operations-Fractions",
            domainCode: "NF",
            domainColorCode: "#EF7C32",
            percentageScore: 34,
            proficiencyLevel: "Proficient",
            fillColor: "#EF7C32",
            strokeColor: "#808285",
            limitDomain: false,
          },
          {
            domainId: 16,
            displayOrder: 5,
            domainName: "Measurement And Data",
            domainCode: "MD",
            domainColorCode: "#F3CE69",
            percentageScore: 53,
            proficiencyLevel: "Proficient",
            fillColor: "#F3CE69",
            strokeColor: "#808285",
            limitDomain: false,
          },
        ],
        studentScores: [
          {
            studentId: 758125,
            displayName: "student 10",
            firstName: "student",
            lastName: "10",
            proficiencyLevel: "Proficient",
            score: 96,
            fillColor: "#88CA22",
            strokeColor: "#88CA22",
            domainScores: [
              {
                domainId: 21,
                displayOrder: 2,
                domainName: "Operations & Algebraic Thinking",
                domainCode: "OA",
                domainColorCode: "#E4412B",
                percentageScore: 43,
                proficiencyLevel: "Proficient",
                fillColor: "#E4412B",
                strokeColor: "#808285",
                limitDomain: false,
              },
              {
                domainId: 19,
                displayOrder: 4,
                domainName: "Number And Operations-Fractions",
                domainCode: "NF",
                domainColorCode: "#EF7C32",
                percentageScore: 34,
                proficiencyLevel: "Proficient",
                fillColor: "#EF7C32",
                strokeColor: "#808285",
                limitDomain: false,
              },
              {
                domainId: 16,
                displayOrder: 5,
                domainName: "Measurement And Data",
                domainCode: "MD",
                domainColorCode: "#F3CE69",
                percentageScore: 53,
                proficiencyLevel: "Proficient",
                fillColor: "#F3CE69",
                strokeColor: "#808285",
                limitDomain: false,
              },
            ],
          },
          {
            studentId: 758126,
            displayName: "Lewandowski Robert",
            firstName: "Lewandowski",
            lastName: "Robert",
            proficiencyLevel: "Below Proficient",
            score: 26,
            fillColor: "#ED7092",
            strokeColor: "#ED7092",
            domainScores: [
              {
                domainId: 21,
                displayOrder: 2,
                domainName: "Operations & Algebraic Thinking",
                domainCode: "OA",
                domainColorCode: "#E4412B",
                percentageScore: 29,
                proficiencyLevel: "Below Proficient",
                fillColor: "#E4412B",
                strokeColor: "#808285",
                limitDomain: false,
              },
              {
                domainId: 19,
                displayOrder: 4,
                domainName: "Number And Operations-Fractions",
                domainCode: "NF",
                domainColorCode: "#EF7C32",
                percentageScore: 11,
                proficiencyLevel: "Below Proficient",
                fillColor: "#EF7C32",
                strokeColor: "#808285",
                limitDomain: false,
              },
              {
                domainId: 16,
                displayOrder: 5,
                domainName: "Measurement And Data",
                domainCode: "MD",
                domainColorCode: "#F3CE69",
                percentageScore: 60,
                proficiencyLevel: "Partially Proficient",
                fillColor: "#F3CE69",
                strokeColor: "#808285",
                limitDomain: false,
              },
            ],
          },
          {
            studentId: 758127,
            displayName: "stu 3",
            firstName: "stu",
            lastName: "3",
            proficiencyLevel: "Below Proficient",
            score: 0,
            fillColor: "#ED7092",
            strokeColor: "#ED7092",
            domainScores: [
              {
                domainId: 21,
                displayOrder: 2,
                domainName: "Operations & Algebraic Thinking",
                domainCode: "OA",
                domainColorCode: "#E4412B",
                percentageScore: 0,
                proficiencyLevel: "Below Proficient",
                fillColor: "#E4412B",
                strokeColor: "#808285",
                limitDomain: false,
              },
              {
                domainId: 19,
                displayOrder: 4,
                domainName: "Number And Operations-Fractions",
                domainCode: "NF",
                domainColorCode: "#EF7C32",
                percentageScore: 0,
                proficiencyLevel: "Below Proficient",
                fillColor: "#EF7C32",
                strokeColor: "#808285",
                limitDomain: false,
              },
              {
                domainId: 16,
                displayOrder: 5,
                domainName: "Measurement And Data",
                domainCode: "MD",
                domainColorCode: "#F3CE69",
                percentageScore: 0,
                proficiencyLevel: "Below Proficient",
                fillColor: "#F3CE69",
                strokeColor: "#808285",
                limitDomain: false,
              },
            ],
          },
        ],
      },
      {
        classId: 66152,
        assessmentId: 80692,
        className: "Class_testjdk",
        teacher: {
          userId: 758124,
          userName: null,
          password: null,
          title: null,
          firstName: "Dat",
          middleName: "",
          lastName: "Tch",
          email: null,
          schoolId: null,
          school: null,
          districtId: null,
          district: null,
          roleId: null,
          role: null,
          status: null,
          statusType: null,
          gradeId: null,
          grade: null,
          gradeEs: null,
          studentId: null,
          learningStyleId: null,
          learningStyle: null,
          createdBy: null,
          modifiedBy: null,
          createdDate: null,
          modifiedDate: null,
          termsAcceptedStatus: null,
          termsVersionAccepted: null,
          termsAcceptedDate: null,
          stateId: null,
          assignable: false,
          numAssign: 0,
          phone: null,
          userLicenses: null,
          className: null,
          classId: null,
          activationCode: null,
          activationExpiredDate: null,
          activationStatus: null,
          authorized: null,
          authorizedBy: null,
          authorizedDate: null,
          hasParent: false,
          lmsId: null,
          instructorRole: null,
          avatar: null,
          avatarSetting: null,
          languageId: null,
          spokenLanguage: null,
          classCode: null,
          parentNum: null,
          salesManager: null,
          linked: null,
          selected: null,
          opt: null,
          optCiu: null,
          optUpdateStatus: null,
          googleClassroomId: null,
          googleRefreshToken: null,
          fullName: "Dat Tch",
          numOfAssignments: null,
          accessCode: null,
          canvasRefreshToken: null,
          importFromCanvas: false,
          canvasImportOption: null,
          studentAssignmentStatus: null,
          cleverId: null,
          emailNotification: null,
          schoologyOauthKey: null,
          schoologyId: null,
          schoologyEnrollmentId: null,
          userDeviceDTOS: null,
          mapStatus: {},
          lockAssignmentTemp: false,
          assignedByTeacher: false,
          allowImpersonation: false,
          classNum: null,
          classNames: null,
          camelFirstLastName: "Dat Tch",
          searchSchoolUser: false,
          resendTeacherVerification: false,
          shownHelp: null,
          needTermAccepted: false,
          allowImpersonated: false,
          firstLastName: "Dat Tch",
          lastFirstName: "Tch, Dat",
          displayName: "Dat Tch",
        },
        score: 0,
        domainScores: [
          {
            domainId: 21,
            displayOrder: 2,
            domainName: "Operations & Algebraic Thinking",
            domainCode: "OA",
            domainColorCode: "#E4412B",
            percentageScore: 0,
            proficiencyLevel: "Below Proficient",
            fillColor: "#E4412B",
            strokeColor: "#808285",
            limitDomain: false,
          },
          {
            domainId: 19,
            displayOrder: 4,
            domainName: "Number And Operations-Fractions",
            domainCode: "NF",
            domainColorCode: "#EF7C32",
            percentageScore: 0,
            proficiencyLevel: "Below Proficient",
            fillColor: "#EF7C32",
            strokeColor: "#808285",
            limitDomain: false,
          },
          {
            domainId: 16,
            displayOrder: 5,
            domainName: "Measurement And Data",
            domainCode: "MD",
            domainColorCode: "#F3CE69",
            percentageScore: 0,
            proficiencyLevel: "Below Proficient",
            fillColor: "#F3CE69",
            strokeColor: "#808285",
            limitDomain: false,
          },
        ],
        studentScores: [
          {
            studentId: 758125,
            displayName: "student 10",
            firstName: "student",
            lastName: "10",
            proficiencyLevel: "Below Proficient",
            score: 0,
            fillColor: "#ED7092",
            strokeColor: "#ED7092",
            domainScores: [
              {
                domainId: 21,
                displayOrder: 2,
                domainName: "Operations & Algebraic Thinking",
                domainCode: "OA",
                domainColorCode: "#E4412B",
                percentageScore: 0,
                proficiencyLevel: "Below Proficient",
                fillColor: "#E4412B",
                strokeColor: "#808285",
                limitDomain: false,
              },
              {
                domainId: 19,
                displayOrder: 4,
                domainName: "Number And Operations-Fractions",
                domainCode: "NF",
                domainColorCode: "#EF7C32",
                percentageScore: 0,
                proficiencyLevel: "Below Proficient",
                fillColor: "#EF7C32",
                strokeColor: "#808285",
                limitDomain: false,
              },
              {
                domainId: 16,
                displayOrder: 5,
                domainName: "Measurement And Data",
                domainCode: "MD",
                domainColorCode: "#F3CE69",
                percentageScore: 0,
                proficiencyLevel: "Below Proficient",
                fillColor: "#F3CE69",
                strokeColor: "#808285",
                limitDomain: false,
              },
            ],
          },
        ],
      },
    ],
  },
  {
    assessmentId: 80693,
    classesScores: [
      {
        classId: 60392,
        assessmentId: 80693,
        className: "Class SM",
        teacher: {
          userId: 758124,
          userName: null,
          password: null,
          title: null,
          firstName: "Dat",
          middleName: "",
          lastName: "Tch",
          email: null,
          schoolId: null,
          school: null,
          districtId: null,
          district: null,
          roleId: null,
          role: null,
          status: null,
          statusType: null,
          gradeId: null,
          grade: null,
          gradeEs: null,
          studentId: null,
          learningStyleId: null,
          learningStyle: null,
          createdBy: null,
          modifiedBy: null,
          createdDate: null,
          modifiedDate: null,
          termsAcceptedStatus: null,
          termsVersionAccepted: null,
          termsAcceptedDate: null,
          stateId: null,
          assignable: false,
          numAssign: 0,
          phone: null,
          userLicenses: null,
          className: null,
          classId: null,
          activationCode: null,
          activationExpiredDate: null,
          activationStatus: null,
          authorized: null,
          authorizedBy: null,
          authorizedDate: null,
          hasParent: false,
          lmsId: null,
          instructorRole: null,
          avatar: null,
          avatarSetting: null,
          languageId: null,
          spokenLanguage: null,
          classCode: null,
          parentNum: null,
          salesManager: null,
          linked: null,
          selected: null,
          opt: null,
          optCiu: null,
          optUpdateStatus: null,
          googleClassroomId: null,
          googleRefreshToken: null,
          fullName: "Dat Tch",
          numOfAssignments: null,
          accessCode: null,
          canvasRefreshToken: null,
          importFromCanvas: false,
          canvasImportOption: null,
          studentAssignmentStatus: null,
          cleverId: null,
          emailNotification: null,
          schoologyOauthKey: null,
          schoologyId: null,
          schoologyEnrollmentId: null,
          userDeviceDTOS: null,
          mapStatus: {},
          lockAssignmentTemp: false,
          assignedByTeacher: false,
          allowImpersonation: false,
          classNum: null,
          classNames: null,
          camelFirstLastName: "Dat Tch",
          searchSchoolUser: false,
          resendTeacherVerification: false,
          shownHelp: null,
          needTermAccepted: false,
          allowImpersonated: false,
          firstLastName: "Dat Tch",
          lastFirstName: "Tch, Dat",
          displayName: "Dat Tch",
        },
        score: 0,
        domainScores: [
          {
            domainId: 21,
            displayOrder: 2,
            domainName: "Operations & Algebraic Thinking",
            domainCode: "OA",
            domainColorCode: "#E4412B",
            percentageScore: 0,
            proficiencyLevel: "Below Proficient",
            fillColor: "#E4412B",
            strokeColor: "#808285",
            limitDomain: false,
          },
          {
            domainId: 19,
            displayOrder: 4,
            domainName: "Number And Operations-Fractions",
            domainCode: "NF",
            domainColorCode: "#EF7C32",
            percentageScore: 0,
            proficiencyLevel: "Below Proficient",
            fillColor: "#EF7C32",
            strokeColor: "#808285",
            limitDomain: false,
          },
          {
            domainId: 16,
            displayOrder: 5,
            domainName: "Measurement And Data",
            domainCode: "MD",
            domainColorCode: "#F3CE69",
            percentageScore: 0,
            proficiencyLevel: "Below Proficient",
            fillColor: "#F3CE69",
            strokeColor: "#808285",
            limitDomain: false,
          },
        ],
        studentScores: [
          {
            studentId: 758132,
            displayName: "Stu SM",
            firstName: "Stu",
            lastName: "SM",
            proficiencyLevel: "Below Proficient",
            score: 0,
            fillColor: "#ED7092",
            strokeColor: "#ED7092",
            domainScores: [
              {
                domainId: 21,
                displayOrder: 2,
                domainName: "Operations & Algebraic Thinking",
                domainCode: "OA",
                domainColorCode: "#E4412B",
                percentageScore: 0,
                proficiencyLevel: "Below Proficient",
                fillColor: "#E4412B",
                strokeColor: "#808285",
                limitDomain: false,
              },
              {
                domainId: 19,
                displayOrder: 4,
                domainName: "Number And Operations-Fractions",
                domainCode: "NF",
                domainColorCode: "#EF7C32",
                percentageScore: 0,
                proficiencyLevel: "Below Proficient",
                fillColor: "#EF7C32",
                strokeColor: "#808285",
                limitDomain: false,
              },
              {
                domainId: 16,
                displayOrder: 5,
                domainName: "Measurement And Data",
                domainCode: "MD",
                domainColorCode: "#F3CE69",
                percentageScore: 0,
                proficiencyLevel: "Below Proficient",
                fillColor: "#F3CE69",
                strokeColor: "#808285",
                limitDomain: false,
              },
            ],
          },
        ],
      },
      {
        classId: 60386,
        assessmentId: 80693,
        className: "Class_1",
        teacher: {
          userId: 758124,
          userName: null,
          password: null,
          title: null,
          firstName: "Dat",
          middleName: "",
          lastName: "Tch",
          email: null,
          schoolId: null,
          school: null,
          districtId: null,
          district: null,
          roleId: null,
          role: null,
          status: null,
          statusType: null,
          gradeId: null,
          grade: null,
          gradeEs: null,
          studentId: null,
          learningStyleId: null,
          learningStyle: null,
          createdBy: null,
          modifiedBy: null,
          createdDate: null,
          modifiedDate: null,
          termsAcceptedStatus: null,
          termsVersionAccepted: null,
          termsAcceptedDate: null,
          stateId: null,
          assignable: false,
          numAssign: 0,
          phone: null,
          userLicenses: null,
          className: null,
          classId: null,
          activationCode: null,
          activationExpiredDate: null,
          activationStatus: null,
          authorized: null,
          authorizedBy: null,
          authorizedDate: null,
          hasParent: false,
          lmsId: null,
          instructorRole: null,
          avatar: null,
          avatarSetting: null,
          languageId: null,
          spokenLanguage: null,
          classCode: null,
          parentNum: null,
          salesManager: null,
          linked: null,
          selected: null,
          opt: null,
          optCiu: null,
          optUpdateStatus: null,
          googleClassroomId: null,
          googleRefreshToken: null,
          fullName: "Dat Tch",
          numOfAssignments: null,
          accessCode: null,
          canvasRefreshToken: null,
          importFromCanvas: false,
          canvasImportOption: null,
          studentAssignmentStatus: null,
          cleverId: null,
          emailNotification: null,
          schoologyOauthKey: null,
          schoologyId: null,
          schoologyEnrollmentId: null,
          userDeviceDTOS: null,
          mapStatus: {},
          lockAssignmentTemp: false,
          assignedByTeacher: false,
          allowImpersonation: false,
          classNum: null,
          classNames: null,
          camelFirstLastName: "Dat Tch",
          searchSchoolUser: false,
          resendTeacherVerification: false,
          shownHelp: null,
          needTermAccepted: false,
          allowImpersonated: false,
          firstLastName: "Dat Tch",
          lastFirstName: "Tch, Dat",
          displayName: "Dat Tch",
        },
        score: 13,
        domainScores: [
          {
            domainId: 21,
            displayOrder: 2,
            domainName: "Operations & Algebraic Thinking",
            domainCode: "OA",
            domainColorCode: "#E4412B",
            percentageScore: 14,
            proficiencyLevel: "Below Proficient",
            fillColor: "#E4412B",
            strokeColor: "#808285",
            limitDomain: false,
          },
          {
            domainId: 19,
            displayOrder: 4,
            domainName: "Number And Operations-Fractions",
            domainCode: "NF",
            domainColorCode: "#EF7C32",
            percentageScore: 7,
            proficiencyLevel: "Below Proficient",
            fillColor: "#EF7C32",
            strokeColor: "#808285",
            limitDomain: false,
          },
          {
            domainId: 16,
            displayOrder: 5,
            domainName: "Measurement And Data",
            domainCode: "MD",
            domainColorCode: "#F3CE69",
            percentageScore: 20,
            proficiencyLevel: "Partially Proficient",
            fillColor: "#F3CE69",
            strokeColor: "#808285",
            limitDomain: false,
          },
        ],
        studentScores: [
          {
            studentId: 758125,
            displayName: "student 10",
            firstName: "student",
            lastName: "10",
            proficiencyLevel: "Below Proficient",
            score: 34,
            fillColor: "#ED7092",
            strokeColor: "#ED7092",
            domainScores: [
              {
                domainId: 21,
                displayOrder: 2,
                domainName: "Operations & Algebraic Thinking",
                domainCode: "OA",
                domainColorCode: "#E4412B",
                percentageScore: 14,
                proficiencyLevel: "Below Proficient",
                fillColor: "#E4412B",
                strokeColor: "#808285",
                limitDomain: false,
              },
              {
                domainId: 19,
                displayOrder: 4,
                domainName: "Number And Operations-Fractions",
                domainCode: "NF",
                domainColorCode: "#EF7C32",
                percentageScore: 7,
                proficiencyLevel: "Below Proficient",
                fillColor: "#EF7C32",
                strokeColor: "#808285",
                limitDomain: false,
              },
              {
                domainId: 16,
                displayOrder: 5,
                domainName: "Measurement And Data",
                domainCode: "MD",
                domainColorCode: "#F3CE69",
                percentageScore: 20,
                proficiencyLevel: "Partially Proficient",
                fillColor: "#F3CE69",
                strokeColor: "#808285",
                limitDomain: false,
              },
            ],
          },
          {
            studentId: 758126,
            displayName: "Lewandowski Robert",
            firstName: "Lewandowski",
            lastName: "Robert",
            proficiencyLevel: "Below Proficient",
            score: 0,
            fillColor: "#ED7092",
            strokeColor: "#ED7092",
            domainScores: [
              {
                domainId: 21,
                displayOrder: 2,
                domainName: "Operations & Algebraic Thinking",
                domainCode: "OA",
                domainColorCode: "#E4412B",
                percentageScore: 0,
                proficiencyLevel: "Below Proficient",
                fillColor: "#E4412B",
                strokeColor: "#808285",
                limitDomain: false,
              },
              {
                domainId: 19,
                displayOrder: 4,
                domainName: "Number And Operations-Fractions",
                domainCode: "NF",
                domainColorCode: "#EF7C32",
                percentageScore: 0,
                proficiencyLevel: "Below Proficient",
                fillColor: "#EF7C32",
                strokeColor: "#808285",
                limitDomain: false,
              },
              {
                domainId: 16,
                displayOrder: 5,
                domainName: "Measurement And Data",
                domainCode: "MD",
                domainColorCode: "#F3CE69",
                percentageScore: 0,
                proficiencyLevel: "Below Proficient",
                fillColor: "#F3CE69",
                strokeColor: "#808285",
                limitDomain: false,
              },
            ],
          },
          {
            studentId: 758127,
            displayName: "stu 3",
            firstName: "stu",
            lastName: "3",
            proficiencyLevel: "Below Proficient",
            score: 0,
            fillColor: "#ED7092",
            strokeColor: "#ED7092",
            domainScores: [
              {
                domainId: 21,
                displayOrder: 2,
                domainName: "Operations & Algebraic Thinking",
                domainCode: "OA",
                domainColorCode: "#E4412B",
                percentageScore: 0,
                proficiencyLevel: "Below Proficient",
                fillColor: "#E4412B",
                strokeColor: "#808285",
                limitDomain: false,
              },
              {
                domainId: 19,
                displayOrder: 4,
                domainName: "Number And Operations-Fractions",
                domainCode: "NF",
                domainColorCode: "#EF7C32",
                percentageScore: 0,
                proficiencyLevel: "Below Proficient",
                fillColor: "#EF7C32",
                strokeColor: "#808285",
                limitDomain: false,
              },
              {
                domainId: 16,
                displayOrder: 5,
                domainName: "Measurement And Data",
                domainCode: "MD",
                domainColorCode: "#F3CE69",
                percentageScore: 0,
                proficiencyLevel: "Below Proficient",
                fillColor: "#F3CE69",
                strokeColor: "#808285",
                limitDomain: false,
              },
            ],
          },
        ],
      },
      {
        classId: 66152,
        assessmentId: 80693,
        className: "Class_testjdk",
        teacher: {
          userId: 758124,
          userName: null,
          password: null,
          title: null,
          firstName: "Dat",
          middleName: "",
          lastName: "Tch",
          email: null,
          schoolId: null,
          school: null,
          districtId: null,
          district: null,
          roleId: null,
          role: null,
          status: null,
          statusType: null,
          gradeId: null,
          grade: null,
          gradeEs: null,
          studentId: null,
          learningStyleId: null,
          learningStyle: null,
          createdBy: null,
          modifiedBy: null,
          createdDate: null,
          modifiedDate: null,
          termsAcceptedStatus: null,
          termsVersionAccepted: null,
          termsAcceptedDate: null,
          stateId: null,
          assignable: false,
          numAssign: 0,
          phone: null,
          userLicenses: null,
          className: null,
          classId: null,
          activationCode: null,
          activationExpiredDate: null,
          activationStatus: null,
          authorized: null,
          authorizedBy: null,
          authorizedDate: null,
          hasParent: false,
          lmsId: null,
          instructorRole: null,
          avatar: null,
          avatarSetting: null,
          languageId: null,
          spokenLanguage: null,
          classCode: null,
          parentNum: null,
          salesManager: null,
          linked: null,
          selected: null,
          opt: null,
          optCiu: null,
          optUpdateStatus: null,
          googleClassroomId: null,
          googleRefreshToken: null,
          fullName: "Dat Tch",
          numOfAssignments: null,
          accessCode: null,
          canvasRefreshToken: null,
          importFromCanvas: false,
          canvasImportOption: null,
          studentAssignmentStatus: null,
          cleverId: null,
          emailNotification: null,
          schoologyOauthKey: null,
          schoologyId: null,
          schoologyEnrollmentId: null,
          userDeviceDTOS: null,
          mapStatus: {},
          lockAssignmentTemp: false,
          assignedByTeacher: false,
          allowImpersonation: false,
          classNum: null,
          classNames: null,
          camelFirstLastName: "Dat Tch",
          searchSchoolUser: false,
          resendTeacherVerification: false,
          shownHelp: null,
          needTermAccepted: false,
          allowImpersonated: false,
          firstLastName: "Dat Tch",
          lastFirstName: "Tch, Dat",
          displayName: "Dat Tch",
        },
        score: 0,
        domainScores: [
          {
            domainId: 21,
            displayOrder: 2,
            domainName: "Operations & Algebraic Thinking",
            domainCode: "OA",
            domainColorCode: "#E4412B",
            percentageScore: 0,
            proficiencyLevel: "Below Proficient",
            fillColor: "#E4412B",
            strokeColor: "#808285",
            limitDomain: false,
          },
          {
            domainId: 19,
            displayOrder: 4,
            domainName: "Number And Operations-Fractions",
            domainCode: "NF",
            domainColorCode: "#EF7C32",
            percentageScore: 0,
            proficiencyLevel: "Below Proficient",
            fillColor: "#EF7C32",
            strokeColor: "#808285",
            limitDomain: false,
          },
          {
            domainId: 16,
            displayOrder: 5,
            domainName: "Measurement And Data",
            domainCode: "MD",
            domainColorCode: "#F3CE69",
            percentageScore: 0,
            proficiencyLevel: "Below Proficient",
            fillColor: "#F3CE69",
            strokeColor: "#808285",
            limitDomain: false,
          },
        ],
        studentScores: [
          {
            studentId: 758125,
            displayName: "student 10",
            firstName: "student",
            lastName: "10",
            proficiencyLevel: "Below Proficient",
            score: 0,
            fillColor: "#ED7092",
            strokeColor: "#ED7092",
            domainScores: [
              {
                domainId: 21,
                displayOrder: 2,
                domainName: "Operations & Algebraic Thinking",
                domainCode: "OA",
                domainColorCode: "#E4412B",
                percentageScore: 0,
                proficiencyLevel: "Below Proficient",
                fillColor: "#E4412B",
                strokeColor: "#808285",
                limitDomain: false,
              },
              {
                domainId: 19,
                displayOrder: 4,
                domainName: "Number And Operations-Fractions",
                domainCode: "NF",
                domainColorCode: "#EF7C32",
                percentageScore: 0,
                proficiencyLevel: "Below Proficient",
                fillColor: "#EF7C32",
                strokeColor: "#808285",
                limitDomain: false,
              },
              {
                domainId: 16,
                displayOrder: 5,
                domainName: "Measurement And Data",
                domainCode: "MD",
                domainColorCode: "#F3CE69",
                percentageScore: 0,
                proficiencyLevel: "Below Proficient",
                fillColor: "#F3CE69",
                strokeColor: "#808285",
                limitDomain: false,
              },
            ],
          },
          {
            studentId: 758126,
            displayName: "Lewandowski Robert",
            firstName: "Lewandowski",
            lastName: "Robert",
            proficiencyLevel: "Below Proficient",
            score: 0,
            fillColor: "#ED7092",
            strokeColor: "#ED7092",
            domainScores: [
              {
                domainId: 21,
                displayOrder: 2,
                domainName: "Operations & Algebraic Thinking",
                domainCode: "OA",
                domainColorCode: "#E4412B",
                percentageScore: 0,
                proficiencyLevel: "Below Proficient",
                fillColor: "#E4412B",
                strokeColor: "#808285",
                limitDomain: false,
              },
              {
                domainId: 19,
                displayOrder: 4,
                domainName: "Number And Operations-Fractions",
                domainCode: "NF",
                domainColorCode: "#EF7C32",
                percentageScore: 0,
                proficiencyLevel: "Below Proficient",
                fillColor: "#EF7C32",
                strokeColor: "#808285",
                limitDomain: false,
              },
              {
                domainId: 16,
                displayOrder: 5,
                domainName: "Measurement And Data",
                domainCode: "MD",
                domainColorCode: "#F3CE69",
                percentageScore: 0,
                proficiencyLevel: "Below Proficient",
                fillColor: "#F3CE69",
                strokeColor: "#808285",
                limitDomain: false,
              },
            ],
          },
        ],
      },
      {
        classId: 79856,
        assessmentId: 80693,
        className: "Dai Class",
        teacher: {
          userId: 758124,
          userName: null,
          password: null,
          title: null,
          firstName: "Dat",
          middleName: "",
          lastName: "Tch",
          email: null,
          schoolId: null,
          school: null,
          districtId: null,
          district: null,
          roleId: null,
          role: null,
          status: null,
          statusType: null,
          gradeId: null,
          grade: null,
          gradeEs: null,
          studentId: null,
          learningStyleId: null,
          learningStyle: null,
          createdBy: null,
          modifiedBy: null,
          createdDate: null,
          modifiedDate: null,
          termsAcceptedStatus: null,
          termsVersionAccepted: null,
          termsAcceptedDate: null,
          stateId: null,
          assignable: false,
          numAssign: 0,
          phone: null,
          userLicenses: null,
          className: null,
          classId: null,
          activationCode: null,
          activationExpiredDate: null,
          activationStatus: null,
          authorized: null,
          authorizedBy: null,
          authorizedDate: null,
          hasParent: false,
          lmsId: null,
          instructorRole: null,
          avatar: null,
          avatarSetting: null,
          languageId: null,
          spokenLanguage: null,
          classCode: null,
          parentNum: null,
          salesManager: null,
          linked: null,
          selected: null,
          opt: null,
          optCiu: null,
          optUpdateStatus: null,
          googleClassroomId: null,
          googleRefreshToken: null,
          fullName: "Dat Tch",
          numOfAssignments: null,
          accessCode: null,
          canvasRefreshToken: null,
          importFromCanvas: false,
          canvasImportOption: null,
          studentAssignmentStatus: null,
          cleverId: null,
          emailNotification: null,
          schoologyOauthKey: null,
          schoologyId: null,
          schoologyEnrollmentId: null,
          userDeviceDTOS: null,
          mapStatus: {},
          lockAssignmentTemp: false,
          assignedByTeacher: false,
          allowImpersonation: false,
          classNum: null,
          classNames: null,
          camelFirstLastName: "Dat Tch",
          searchSchoolUser: false,
          resendTeacherVerification: false,
          shownHelp: null,
          needTermAccepted: false,
          allowImpersonated: false,
          firstLastName: "Dat Tch",
          lastFirstName: "Tch, Dat",
          displayName: "Dat Tch",
        },
        score: 6,
        domainScores: [
          {
            domainId: 21,
            displayOrder: 2,
            domainName: "Operations & Algebraic Thinking",
            domainCode: "OA",
            domainColorCode: "#E4412B",
            percentageScore: 20,
            proficiencyLevel: "Below Proficient",
            fillColor: "#E4412B",
            strokeColor: "#808285",
            limitDomain: false,
          },
          {
            domainId: 19,
            displayOrder: 4,
            domainName: "Number And Operations-Fractions",
            domainCode: "NF",
            domainColorCode: "#EF7C32",
            percentageScore: 0,
            proficiencyLevel: "Below Proficient",
            fillColor: "#EF7C32",
            strokeColor: "#808285",
            limitDomain: false,
          },
          {
            domainId: 16,
            displayOrder: 5,
            domainName: "Measurement And Data",
            domainCode: "MD",
            domainColorCode: "#F3CE69",
            percentageScore: 0,
            proficiencyLevel: "Below Proficient",
            fillColor: "#F3CE69",
            strokeColor: "#808285",
            limitDomain: false,
          },
        ],
        studentScores: [
          {
            studentId: 758127,
            displayName: "stu 3",
            firstName: "stu",
            lastName: "3",
            proficiencyLevel: "Below Proficient",
            score: 11,
            fillColor: "#ED7092",
            strokeColor: "#ED7092",
            domainScores: [
              {
                domainId: 21,
                displayOrder: 2,
                domainName: "Operations & Algebraic Thinking",
                domainCode: "OA",
                domainColorCode: "#E4412B",
                percentageScore: 20,
                proficiencyLevel: "Below Proficient",
                fillColor: "#E4412B",
                strokeColor: "#808285",
                limitDomain: false,
              },
              {
                domainId: 19,
                displayOrder: 4,
                domainName: "Number And Operations-Fractions",
                domainCode: "NF",
                domainColorCode: "#EF7C32",
                percentageScore: 0,
                proficiencyLevel: "Below Proficient",
                fillColor: "#EF7C32",
                strokeColor: "#808285",
                limitDomain: false,
              },
              {
                domainId: 16,
                displayOrder: 5,
                domainName: "Measurement And Data",
                domainCode: "MD",
                domainColorCode: "#F3CE69",
                percentageScore: 0,
                proficiencyLevel: "Below Proficient",
                fillColor: "#F3CE69",
                strokeColor: "#808285",
                limitDomain: false,
              },
            ],
          },
        ],
      },
    ],
  },
];

export const aTestScore: TestScoreResponseType = {
  assessmentId: 80693,
  // 4 charts bar classesScores.length
  classesScores: [
    {
      classId: 60392,
      assessmentId: 80693,
      className: "Class SM",
      teacher: {
        userId: 758124,
        userName: null,
        password: null,
        title: null,
        firstName: "Dat",
        middleName: "",
        lastName: "Tch",
        email: null,
        schoolId: null,
        school: null,
        districtId: null,
        district: null,
        roleId: null,
        role: null,
        status: null,
        statusType: null,
        gradeId: null,
        grade: null,
        gradeEs: null,
        studentId: null,
        learningStyleId: null,
        learningStyle: null,
        createdBy: null,
        modifiedBy: null,
        createdDate: null,
        modifiedDate: null,
        termsAcceptedStatus: null,
        termsVersionAccepted: null,
        termsAcceptedDate: null,
        stateId: null,
        assignable: false,
        numAssign: 0,
        phone: null,
        userLicenses: null,
        className: null,
        classId: null,
        activationCode: null,
        activationExpiredDate: null,
        activationStatus: null,
        authorized: null,
        authorizedBy: null,
        authorizedDate: null,
        hasParent: false,
        lmsId: null,
        instructorRole: null,
        avatar: null,
        avatarSetting: null,
        languageId: null,
        spokenLanguage: null,
        classCode: null,
        parentNum: null,
        salesManager: null,
        linked: null,
        selected: null,
        opt: null,
        optCiu: null,
        optUpdateStatus: null,
        googleClassroomId: null,
        googleRefreshToken: null,
        fullName: "Dat Tch",
        numOfAssignments: null,
        accessCode: null,
        canvasRefreshToken: null,
        importFromCanvas: false,
        canvasImportOption: null,
        studentAssignmentStatus: null,
        cleverId: null,
        emailNotification: null,
        schoologyOauthKey: null,
        schoologyId: null,
        schoologyEnrollmentId: null,
        userDeviceDTOS: null,
        mapStatus: {},
        lockAssignmentTemp: false,
        assignedByTeacher: false,
        allowImpersonation: false,
        classNum: null,
        classNames: null,
        camelFirstLastName: "Dat Tch",
        searchSchoolUser: false,
        resendTeacherVerification: false,
        shownHelp: null,
        needTermAccepted: false,
        allowImpersonated: false,
        firstLastName: "Dat Tch",
        lastFirstName: "Tch, Dat",
        displayName: "Dat Tch",
      },
      score: 0,
      // 3 stack = domainScores.length
      domainScores: [
        {
          domainId: 21,
          displayOrder: 2,
          domainName: "Operations & Algebraic Thinking",
          domainCode: "OA",
          domainColorCode: "#E4412B",
          percentageScore: 0,
          proficiencyLevel: "Below Proficient",
          fillColor: "#E4412B",
          strokeColor: "#808285",
          limitDomain: false,
        },
        {
          domainId: 19,
          displayOrder: 4,
          domainName: "Number And Operations-Fractions",
          domainCode: "NF",
          domainColorCode: "#EF7C32",
          percentageScore: 0,
          proficiencyLevel: "Below Proficient",
          fillColor: "#EF7C32",
          strokeColor: "#808285",
          limitDomain: false,
        },
        {
          domainId: 16,
          displayOrder: 5,
          domainName: "Measurement And Data",
          domainCode: "MD",
          domainColorCode: "#F3CE69",
          percentageScore: 0,
          proficiencyLevel: "Below Proficient",
          fillColor: "#F3CE69",
          strokeColor: "#808285",
          limitDomain: false,
        },
      ],
      studentScores: [
        {
          studentId: 758132,
          displayName: "Stu SM",
          firstName: "Stu",
          lastName: "SM",
          proficiencyLevel: "Below Proficient",
          score: 0,
          fillColor: "#ED7092",
          strokeColor: "#ED7092",
          domainScores: [
            {
              domainId: 21,
              displayOrder: 2,
              domainName: "Operations & Algebraic Thinking",
              domainCode: "OA",
              domainColorCode: "#E4412B",
              percentageScore: 0,
              proficiencyLevel: "Below Proficient",
              fillColor: "#E4412B",
              strokeColor: "#808285",
              limitDomain: false,
            },
            {
              domainId: 19,
              displayOrder: 4,
              domainName: "Number And Operations-Fractions",
              domainCode: "NF",
              domainColorCode: "#EF7C32",
              percentageScore: 0,
              proficiencyLevel: "Below Proficient",
              fillColor: "#EF7C32",
              strokeColor: "#808285",
              limitDomain: false,
            },
            {
              domainId: 16,
              displayOrder: 5,
              domainName: "Measurement And Data",
              domainCode: "MD",
              domainColorCode: "#F3CE69",
              percentageScore: 0,
              proficiencyLevel: "Below Proficient",
              fillColor: "#F3CE69",
              strokeColor: "#808285",
              limitDomain: false,
            },
          ],
        },
      ],
    },
    {
      classId: 60386,
      assessmentId: 80693,
      className: "Class_1",
      teacher: {
        userId: 758124,
        userName: null,
        password: null,
        title: null,
        firstName: "Dat",
        middleName: "",
        lastName: "Tch",
        email: null,
        schoolId: null,
        school: null,
        districtId: null,
        district: null,
        roleId: null,
        role: null,
        status: null,
        statusType: null,
        gradeId: null,
        grade: null,
        gradeEs: null,
        studentId: null,
        learningStyleId: null,
        learningStyle: null,
        createdBy: null,
        modifiedBy: null,
        createdDate: null,
        modifiedDate: null,
        termsAcceptedStatus: null,
        termsVersionAccepted: null,
        termsAcceptedDate: null,
        stateId: null,
        assignable: false,
        numAssign: 0,
        phone: null,
        userLicenses: null,
        className: null,
        classId: null,
        activationCode: null,
        activationExpiredDate: null,
        activationStatus: null,
        authorized: null,
        authorizedBy: null,
        authorizedDate: null,
        hasParent: false,
        lmsId: null,
        instructorRole: null,
        avatar: null,
        avatarSetting: null,
        languageId: null,
        spokenLanguage: null,
        classCode: null,
        parentNum: null,
        salesManager: null,
        linked: null,
        selected: null,
        opt: null,
        optCiu: null,
        optUpdateStatus: null,
        googleClassroomId: null,
        googleRefreshToken: null,
        fullName: "Dat Tch",
        numOfAssignments: null,
        accessCode: null,
        canvasRefreshToken: null,
        importFromCanvas: false,
        canvasImportOption: null,
        studentAssignmentStatus: null,
        cleverId: null,
        emailNotification: null,
        schoologyOauthKey: null,
        schoologyId: null,
        schoologyEnrollmentId: null,
        userDeviceDTOS: null,
        mapStatus: {},
        lockAssignmentTemp: false,
        assignedByTeacher: false,
        allowImpersonation: false,
        classNum: null,
        classNames: null,
        camelFirstLastName: "Dat Tch",
        searchSchoolUser: false,
        resendTeacherVerification: false,
        shownHelp: null,
        needTermAccepted: false,
        allowImpersonated: false,
        firstLastName: "Dat Tch",
        lastFirstName: "Tch, Dat",
        displayName: "Dat Tch",
      },
      score: 13,
      domainScores: [
        {
          domainId: 21,
          displayOrder: 2,
          domainName: "Operations & Algebraic Thinking",
          domainCode: "OA",
          domainColorCode: "#E4412B",
          percentageScore: 14,
          proficiencyLevel: "Below Proficient",
          fillColor: "#E4412B",
          strokeColor: "#808285",
          limitDomain: false,
        },
        {
          domainId: 19,
          displayOrder: 4,
          domainName: "Number And Operations-Fractions",
          domainCode: "NF",
          domainColorCode: "#EF7C32",
          percentageScore: 7,
          proficiencyLevel: "Below Proficient",
          fillColor: "#EF7C32",
          strokeColor: "#808285",
          limitDomain: false,
        },
        {
          domainId: 16,
          displayOrder: 5,
          domainName: "Measurement And Data",
          domainCode: "MD",
          domainColorCode: "#F3CE69",
          percentageScore: 20,
          proficiencyLevel: "Partially Proficient",
          fillColor: "#F3CE69",
          strokeColor: "#808285",
          limitDomain: false,
        },
      ],
      studentScores: [
        {
          studentId: 758125,
          displayName: "student 10",
          firstName: "student",
          lastName: "10",
          proficiencyLevel: "Below Proficient",
          score: 34,
          fillColor: "#ED7092",
          strokeColor: "#ED7092",
          domainScores: [
            {
              domainId: 21,
              displayOrder: 2,
              domainName: "Operations & Algebraic Thinking",
              domainCode: "OA",
              domainColorCode: "#E4412B",
              percentageScore: 14,
              proficiencyLevel: "Below Proficient",
              fillColor: "#E4412B",
              strokeColor: "#808285",
              limitDomain: false,
            },
            {
              domainId: 19,
              displayOrder: 4,
              domainName: "Number And Operations-Fractions",
              domainCode: "NF",
              domainColorCode: "#EF7C32",
              percentageScore: 7,
              proficiencyLevel: "Below Proficient",
              fillColor: "#EF7C32",
              strokeColor: "#808285",
              limitDomain: false,
            },
            {
              domainId: 16,
              displayOrder: 5,
              domainName: "Measurement And Data",
              domainCode: "MD",
              domainColorCode: "#F3CE69",
              percentageScore: 20,
              proficiencyLevel: "Partially Proficient",
              fillColor: "#F3CE69",
              strokeColor: "#808285",
              limitDomain: false,
            },
          ],
        },
        {
          studentId: 758126,
          displayName: "Lewandowski Robert",
          firstName: "Lewandowski",
          lastName: "Robert",
          proficiencyLevel: "Below Proficient",
          score: 0,
          fillColor: "#ED7092",
          strokeColor: "#ED7092",
          domainScores: [
            {
              domainId: 21,
              displayOrder: 2,
              domainName: "Operations & Algebraic Thinking",
              domainCode: "OA",
              domainColorCode: "#E4412B",
              percentageScore: 0,
              proficiencyLevel: "Below Proficient",
              fillColor: "#E4412B",
              strokeColor: "#808285",
              limitDomain: false,
            },
            {
              domainId: 19,
              displayOrder: 4,
              domainName: "Number And Operations-Fractions",
              domainCode: "NF",
              domainColorCode: "#EF7C32",
              percentageScore: 0,
              proficiencyLevel: "Below Proficient",
              fillColor: "#EF7C32",
              strokeColor: "#808285",
              limitDomain: false,
            },
            {
              domainId: 16,
              displayOrder: 5,
              domainName: "Measurement And Data",
              domainCode: "MD",
              domainColorCode: "#F3CE69",
              percentageScore: 0,
              proficiencyLevel: "Below Proficient",
              fillColor: "#F3CE69",
              strokeColor: "#808285",
              limitDomain: false,
            },
          ],
        },
        {
          studentId: 758127,
          displayName: "stu 3",
          firstName: "stu",
          lastName: "3",
          proficiencyLevel: "Below Proficient",
          score: 0,
          fillColor: "#ED7092",
          strokeColor: "#ED7092",
          domainScores: [
            {
              domainId: 21,
              displayOrder: 2,
              domainName: "Operations & Algebraic Thinking",
              domainCode: "OA",
              domainColorCode: "#E4412B",
              percentageScore: 0,
              proficiencyLevel: "Below Proficient",
              fillColor: "#E4412B",
              strokeColor: "#808285",
              limitDomain: false,
            },
            {
              domainId: 19,
              displayOrder: 4,
              domainName: "Number And Operations-Fractions",
              domainCode: "NF",
              domainColorCode: "#EF7C32",
              percentageScore: 0,
              proficiencyLevel: "Below Proficient",
              fillColor: "#EF7C32",
              strokeColor: "#808285",
              limitDomain: false,
            },
            {
              domainId: 16,
              displayOrder: 5,
              domainName: "Measurement And Data",
              domainCode: "MD",
              domainColorCode: "#F3CE69",
              percentageScore: 0,
              proficiencyLevel: "Below Proficient",
              fillColor: "#F3CE69",
              strokeColor: "#808285",
              limitDomain: false,
            },
          ],
        },
      ],
    },
    {
      classId: 66152,
      assessmentId: 80693,
      className: "Class_testjdk",
      teacher: {
        userId: 758124,
        userName: null,
        password: null,
        title: null,
        firstName: "Dat",
        middleName: "",
        lastName: "Tch",
        email: null,
        schoolId: null,
        school: null,
        districtId: null,
        district: null,
        roleId: null,
        role: null,
        status: null,
        statusType: null,
        gradeId: null,
        grade: null,
        gradeEs: null,
        studentId: null,
        learningStyleId: null,
        learningStyle: null,
        createdBy: null,
        modifiedBy: null,
        createdDate: null,
        modifiedDate: null,
        termsAcceptedStatus: null,
        termsVersionAccepted: null,
        termsAcceptedDate: null,
        stateId: null,
        assignable: false,
        numAssign: 0,
        phone: null,
        userLicenses: null,
        className: null,
        classId: null,
        activationCode: null,
        activationExpiredDate: null,
        activationStatus: null,
        authorized: null,
        authorizedBy: null,
        authorizedDate: null,
        hasParent: false,
        lmsId: null,
        instructorRole: null,
        avatar: null,
        avatarSetting: null,
        languageId: null,
        spokenLanguage: null,
        classCode: null,
        parentNum: null,
        salesManager: null,
        linked: null,
        selected: null,
        opt: null,
        optCiu: null,
        optUpdateStatus: null,
        googleClassroomId: null,
        googleRefreshToken: null,
        fullName: "Dat Tch",
        numOfAssignments: null,
        accessCode: null,
        canvasRefreshToken: null,
        importFromCanvas: false,
        canvasImportOption: null,
        studentAssignmentStatus: null,
        cleverId: null,
        emailNotification: null,
        schoologyOauthKey: null,
        schoologyId: null,
        schoologyEnrollmentId: null,
        userDeviceDTOS: null,
        mapStatus: {},
        lockAssignmentTemp: false,
        assignedByTeacher: false,
        allowImpersonation: false,
        classNum: null,
        classNames: null,
        camelFirstLastName: "Dat Tch",
        searchSchoolUser: false,
        resendTeacherVerification: false,
        shownHelp: null,
        needTermAccepted: false,
        allowImpersonated: false,
        firstLastName: "Dat Tch",
        lastFirstName: "Tch, Dat",
        displayName: "Dat Tch",
      },
      score: 0,
      domainScores: [
        {
          domainId: 21,
          displayOrder: 2,
          domainName: "Operations & Algebraic Thinking",
          domainCode: "OA",
          domainColorCode: "#E4412B",
          percentageScore: 0,
          proficiencyLevel: "Below Proficient",
          fillColor: "#E4412B",
          strokeColor: "#808285",
          limitDomain: false,
        },
        {
          domainId: 19,
          displayOrder: 4,
          domainName: "Number And Operations-Fractions",
          domainCode: "NF",
          domainColorCode: "#EF7C32",
          percentageScore: 0,
          proficiencyLevel: "Below Proficient",
          fillColor: "#EF7C32",
          strokeColor: "#808285",
          limitDomain: false,
        },
        {
          domainId: 16,
          displayOrder: 5,
          domainName: "Measurement And Data",
          domainCode: "MD",
          domainColorCode: "#F3CE69",
          percentageScore: 0,
          proficiencyLevel: "Below Proficient",
          fillColor: "#F3CE69",
          strokeColor: "#808285",
          limitDomain: false,
        },
      ],
      studentScores: [
        {
          studentId: 758125,
          displayName: "student 10",
          firstName: "student",
          lastName: "10",
          proficiencyLevel: "Below Proficient",
          score: 0,
          fillColor: "#ED7092",
          strokeColor: "#ED7092",
          domainScores: [
            {
              domainId: 21,
              displayOrder: 2,
              domainName: "Operations & Algebraic Thinking",
              domainCode: "OA",
              domainColorCode: "#E4412B",
              percentageScore: 0,
              proficiencyLevel: "Below Proficient",
              fillColor: "#E4412B",
              strokeColor: "#808285",
              limitDomain: false,
            },
            {
              domainId: 19,
              displayOrder: 4,
              domainName: "Number And Operations-Fractions",
              domainCode: "NF",
              domainColorCode: "#EF7C32",
              percentageScore: 0,
              proficiencyLevel: "Below Proficient",
              fillColor: "#EF7C32",
              strokeColor: "#808285",
              limitDomain: false,
            },
            {
              domainId: 16,
              displayOrder: 5,
              domainName: "Measurement And Data",
              domainCode: "MD",
              domainColorCode: "#F3CE69",
              percentageScore: 0,
              proficiencyLevel: "Below Proficient",
              fillColor: "#F3CE69",
              strokeColor: "#808285",
              limitDomain: false,
            },
          ],
        },
        {
          studentId: 758126,
          displayName: "Lewandowski Robert",
          firstName: "Lewandowski",
          lastName: "Robert",
          proficiencyLevel: "Below Proficient",
          score: 0,
          fillColor: "#ED7092",
          strokeColor: "#ED7092",
          domainScores: [
            {
              domainId: 21,
              displayOrder: 2,
              domainName: "Operations & Algebraic Thinking",
              domainCode: "OA",
              domainColorCode: "#E4412B",
              percentageScore: 0,
              proficiencyLevel: "Below Proficient",
              fillColor: "#E4412B",
              strokeColor: "#808285",
              limitDomain: false,
            },
            {
              domainId: 19,
              displayOrder: 4,
              domainName: "Number And Operations-Fractions",
              domainCode: "NF",
              domainColorCode: "#EF7C32",
              percentageScore: 0,
              proficiencyLevel: "Below Proficient",
              fillColor: "#EF7C32",
              strokeColor: "#808285",
              limitDomain: false,
            },
            {
              domainId: 16,
              displayOrder: 5,
              domainName: "Measurement And Data",
              domainCode: "MD",
              domainColorCode: "#F3CE69",
              percentageScore: 0,
              proficiencyLevel: "Below Proficient",
              fillColor: "#F3CE69",
              strokeColor: "#808285",
              limitDomain: false,
            },
          ],
        },
      ],
    },
    {
      classId: 79856,
      assessmentId: 80693,
      className: "Dai Class",
      teacher: {
        userId: 758124,
        userName: null,
        password: null,
        title: null,
        firstName: "Dat",
        middleName: "",
        lastName: "Tch",
        email: null,
        schoolId: null,
        school: null,
        districtId: null,
        district: null,
        roleId: null,
        role: null,
        status: null,
        statusType: null,
        gradeId: null,
        grade: null,
        gradeEs: null,
        studentId: null,
        learningStyleId: null,
        learningStyle: null,
        createdBy: null,
        modifiedBy: null,
        createdDate: null,
        modifiedDate: null,
        termsAcceptedStatus: null,
        termsVersionAccepted: null,
        termsAcceptedDate: null,
        stateId: null,
        assignable: false,
        numAssign: 0,
        phone: null,
        userLicenses: null,
        className: null,
        classId: null,
        activationCode: null,
        activationExpiredDate: null,
        activationStatus: null,
        authorized: null,
        authorizedBy: null,
        authorizedDate: null,
        hasParent: false,
        lmsId: null,
        instructorRole: null,
        avatar: null,
        avatarSetting: null,
        languageId: null,
        spokenLanguage: null,
        classCode: null,
        parentNum: null,
        salesManager: null,
        linked: null,
        selected: null,
        opt: null,
        optCiu: null,
        optUpdateStatus: null,
        googleClassroomId: null,
        googleRefreshToken: null,
        fullName: "Dat Tch",
        numOfAssignments: null,
        accessCode: null,
        canvasRefreshToken: null,
        importFromCanvas: false,
        canvasImportOption: null,
        studentAssignmentStatus: null,
        cleverId: null,
        emailNotification: null,
        schoologyOauthKey: null,
        schoologyId: null,
        schoologyEnrollmentId: null,
        userDeviceDTOS: null,
        mapStatus: {},
        lockAssignmentTemp: false,
        assignedByTeacher: false,
        allowImpersonation: false,
        classNum: null,
        classNames: null,
        camelFirstLastName: "Dat Tch",
        searchSchoolUser: false,
        resendTeacherVerification: false,
        shownHelp: null,
        needTermAccepted: false,
        allowImpersonated: false,
        firstLastName: "Dat Tch",
        lastFirstName: "Tch, Dat",
        displayName: "Dat Tch",
      },
      score: 6,
      domainScores: [
        {
          domainId: 21,
          displayOrder: 2,
          domainName: "Operations & Algebraic Thinking",
          domainCode: "OA",
          domainColorCode: "#E4412B",
          percentageScore: 20,
          proficiencyLevel: "Below Proficient",
          fillColor: "#E4412B",
          strokeColor: "#808285",
          limitDomain: false,
        },
        {
          domainId: 19,
          displayOrder: 4,
          domainName: "Number And Operations-Fractions",
          domainCode: "NF",
          domainColorCode: "#EF7C32",
          percentageScore: 0,
          proficiencyLevel: "Below Proficient",
          fillColor: "#EF7C32",
          strokeColor: "#808285",
          limitDomain: false,
        },
        {
          domainId: 16,
          displayOrder: 5,
          domainName: "Measurement And Data",
          domainCode: "MD",
          domainColorCode: "#F3CE69",
          percentageScore: 0,
          proficiencyLevel: "Below Proficient",
          fillColor: "#F3CE69",
          strokeColor: "#808285",
          limitDomain: false,
        },
      ],
      studentScores: [
        {
          studentId: 758127,
          displayName: "stu 3",
          firstName: "stu",
          lastName: "3",
          proficiencyLevel: "Below Proficient",
          score: 11,
          fillColor: "#ED7092",
          strokeColor: "#ED7092",
          domainScores: [
            {
              domainId: 21,
              displayOrder: 2,
              domainName: "Operations & Algebraic Thinking",
              domainCode: "OA",
              domainColorCode: "#E4412B",
              percentageScore: 20,
              proficiencyLevel: "Below Proficient",
              fillColor: "#E4412B",
              strokeColor: "#808285",
              limitDomain: false,
            },
            {
              domainId: 19,
              displayOrder: 4,
              domainName: "Number And Operations-Fractions",
              domainCode: "NF",
              domainColorCode: "#EF7C32",
              percentageScore: 0,
              proficiencyLevel: "Below Proficient",
              fillColor: "#EF7C32",
              strokeColor: "#808285",
              limitDomain: false,
            },
            {
              domainId: 16,
              displayOrder: 5,
              domainName: "Measurement And Data",
              domainCode: "MD",
              domainColorCode: "#F3CE69",
              percentageScore: 0,
              proficiencyLevel: "Below Proficient",
              fillColor: "#F3CE69",
              strokeColor: "#808285",
              limitDomain: false,
            },
          ],
        },
      ],
    },
  ],
};
