import React from "react";
import ChartLayout from "./ChartLayout";
import styled from "styled-components";
export const _a = [
  {
    studentId: 593355,
    displayName: "FA10 FA10",
    firstName: "FA10",
    lastName: "FA10",
    proficiencyLevel: "Below Proficient",
    score: 0,
    fillColor: "#ED7092",
    strokeColor: "#ED7092",
    toScore: 0,
    toProficiencyLevel: "Below Proficient",
    toStrokeColor: "#ED7092",
    domainScores: [
      {
        domainId: 39,
        displayOrder: null,
        domainName: "Key Ideas and Details: Literary Texts",
        domainCode: "RL_KID",
        domainColorCode: "#998675",
        percentageScore: 0,
        proficiencyLevel: "Below Proficient",
        fillColor: "#998675",
        strokeColor: "#808285",
        growthPercentage: 0,
        toPercentageScore: 0,
        toProficiencyLevel: "Below Proficient",
        toFillColor: "#998675",
        toStrokeColor: "#808285",
        limitDomain: true,
      },
      {
        domainId: 40,
        displayOrder: null,
        domainName: "Craft and Structure: Literary Texts",
        domainCode: "RL_CS",
        domainColorCode: "#E4412B",
        percentageScore: 0,
        proficiencyLevel: "Below Proficient",
        fillColor: "#E4412B",
        strokeColor: "#808285",
        growthPercentage: 0,
        toPercentageScore: 0,
        toProficiencyLevel: "Below Proficient",
        toFillColor: "#E4412B",
        toStrokeColor: "#808285",
        limitDomain: true,
      },
      {
        domainId: 42,
        displayOrder: null,
        domainName: "Key Ideas and Details: Informational Texts",
        domainCode: "RI_KID",
        domainColorCode: "#F3CE69",
        percentageScore: 0,
        proficiencyLevel: "Below Proficient",
        fillColor: "#F3CE69",
        strokeColor: "#808285",
        growthPercentage: 0,
        toPercentageScore: 0,
        toProficiencyLevel: "Below Proficient",
        toFillColor: "#F3CE69",
        toStrokeColor: "#808285",
        limitDomain: true,
      },
      {
        domainId: 43,
        displayOrder: null,
        domainName: "Craft and Structure: Informational Texts",
        domainCode: "RI_CS",
        domainColorCode: "#C88EB7",
        percentageScore: 0,
        proficiencyLevel: "Below Proficient",
        fillColor: "#C88EB7",
        strokeColor: "#808285",
        growthPercentage: 0,
        toPercentageScore: 0,
        toProficiencyLevel: "Below Proficient",
        toFillColor: "#C88EB7",
        toStrokeColor: "#808285",
        limitDomain: true,
      },
      {
        domainId: 44,
        displayOrder: null,
        domainName: "Integration of Knowledge and Ideas: Informational Texts",
        domainCode: "RI_IKI",
        domainColorCode: "#00B9B4",
        percentageScore: 0,
        proficiencyLevel: "Below Proficient",
        fillColor: "#00B9B4",
        strokeColor: "#808285",
        growthPercentage: 0,
        toPercentageScore: 0,
        toProficiencyLevel: "Below Proficient",
        toFillColor: "#00B9B4",
        toStrokeColor: "#808285",
        limitDomain: true,
      },
    ],
  },
  {
    studentId: 593354,
    displayName: "FA11 FA11",
    firstName: "FA11",
    lastName: "FA11",
    proficiencyLevel: "Below Proficient",
    score: 0,
    fillColor: "#ED7092",
    strokeColor: "#ED7092",
    toScore: 100,
    toProficiencyLevel: "Proficient",
    toStrokeColor: "#88CA22",
    domainScores: [
      {
        domainId: 39,
        displayOrder: null,
        domainName: "Key Ideas and Details: Literary Texts",
        domainCode: "RL_KID",
        domainColorCode: "#998675",
        percentageScore: 0,
        proficiencyLevel: "Below Proficient",
        fillColor: "#998675",
        strokeColor: "#808285",
        growthPercentage: 100,
        toPercentageScore: 100,
        toProficiencyLevel: "Proficient",
        toFillColor: "#998675",
        toStrokeColor: "#808285",
        limitDomain: true,
      },
      {
        domainId: 40,
        displayOrder: null,
        domainName: "Craft and Structure: Literary Texts",
        domainCode: "RL_CS",
        domainColorCode: "#E4412B",
        percentageScore: 0,
        proficiencyLevel: "Below Proficient",
        fillColor: "#E4412B",
        strokeColor: "#808285",
        growthPercentage: 100,
        toPercentageScore: 100,
        toProficiencyLevel: "Proficient",
        toFillColor: "#E4412B",
        toStrokeColor: "#808285",
        limitDomain: true,
      },
      {
        domainId: 42,
        displayOrder: null,
        domainName: "Key Ideas and Details: Informational Texts",
        domainCode: "RI_KID",
        domainColorCode: "#F3CE69",
        percentageScore: 0,
        proficiencyLevel: "Below Proficient",
        fillColor: "#F3CE69",
        strokeColor: "#808285",
        growthPercentage: 100,
        toPercentageScore: 100,
        toProficiencyLevel: "Proficient",
        toFillColor: "#F3CE69",
        toStrokeColor: "#808285",
        limitDomain: true,
      },
      {
        domainId: 43,
        displayOrder: null,
        domainName: "Craft and Structure: Informational Texts",
        domainCode: "RI_CS",
        domainColorCode: "#C88EB7",
        percentageScore: 0,
        proficiencyLevel: "Below Proficient",
        fillColor: "#C88EB7",
        strokeColor: "#808285",
        growthPercentage: 100,
        toPercentageScore: 100,
        toProficiencyLevel: "Proficient",
        toFillColor: "#C88EB7",
        toStrokeColor: "#808285",
        limitDomain: true,
      },
      {
        domainId: 44,
        displayOrder: null,
        domainName: "Integration of Knowledge and Ideas: Informational Texts",
        domainCode: "RI_IKI",
        domainColorCode: "#00B9B4",
        percentageScore: 0,
        proficiencyLevel: "Below Proficient",
        fillColor: "#00B9B4",
        strokeColor: "#808285",
        growthPercentage: 100,
        toPercentageScore: 100,
        toProficiencyLevel: "Proficient",
        toFillColor: "#00B9B4",
        toStrokeColor: "#808285",
        limitDomain: true,
      },
    ],
  },
  {
    studentId: 593353,
    displayName: "FA12 FA12",
    firstName: "FA12",
    lastName: "FA12",
    proficiencyLevel: "Partially Proficient",
    score: 61,
    fillColor: "#F5C839",
    strokeColor: "#F5C839",
    toScore: 88,
    toProficiencyLevel: "Proficient",
    toStrokeColor: "#88CA22",
    domainScores: [
      {
        domainId: 39,
        displayOrder: null,
        domainName: "Key Ideas and Details: Literary Texts",
        domainCode: "RL_KID",
        domainColorCode: "#998675",
        percentageScore: 80, // react
        proficiencyLevel: "Proficient",
        fillColor: "#998675",
        strokeColor: "#808285",
        growthPercentage: -10, //
        toPercentageScore: 70, // circle
        toProficiencyLevel: "Partially Proficient",
        toFillColor: "#998675",
        toStrokeColor: "#808285",
        limitDomain: true,
      },
      {
        domainId: 40,
        displayOrder: null,
        domainName: "Craft and Structure: Literary Texts",
        domainCode: "RL_CS",
        domainColorCode: "#E4412B",
        percentageScore: 40,
        proficiencyLevel: "Below Proficient",
        fillColor: "#E4412B",
        strokeColor: "#808285",
        growthPercentage: 60,
        toPercentageScore: 100,
        toProficiencyLevel: "Proficient",
        toFillColor: "#E4412B",
        toStrokeColor: "#808285",
        limitDomain: true,
      },
      {
        domainId: 42,
        displayOrder: null,
        domainName: "Key Ideas and Details: Informational Texts",
        domainCode: "RI_KID",
        domainColorCode: "#F3CE69",
        percentageScore: 88,
        proficiencyLevel: "Proficient",
        fillColor: "#F3CE69",
        strokeColor: "#808285",
        growthPercentage: -11,
        toPercentageScore: 77,
        toProficiencyLevel: "Partially Proficient",
        toFillColor: "#F3CE69",
        toStrokeColor: "#808285",
        limitDomain: true,
      },
      {
        domainId: 43,
        displayOrder: null,
        domainName: "Craft and Structure: Informational Texts",
        domainCode: "RI_CS",
        domainColorCode: "#C88EB7",
        percentageScore: 42,
        proficiencyLevel: "Below Proficient",
        fillColor: "#C88EB7",
        strokeColor: "#808285",
        growthPercentage: 58,
        toPercentageScore: 100,
        toProficiencyLevel: "Proficient",
        toFillColor: "#C88EB7",
        toStrokeColor: "#808285",
        limitDomain: true,
      },
      {
        domainId: 44,
        displayOrder: null,
        domainName: "Integration of Knowledge and Ideas: Informational Texts",
        domainCode: "RI_IKI",
        domainColorCode: "#00B9B4",
        percentageScore: 57,
        proficiencyLevel: "Partially Proficient",
        fillColor: "#00B9B4",
        strokeColor: "#808285",
        growthPercentage: 43,
        toPercentageScore: 100,
        toProficiencyLevel: "Proficient",
        toFillColor: "#00B9B4",
        toStrokeColor: "#808285",
        limitDomain: true,
      },
    ],
  },
];
function Growth() {
  return <ChartLayout />;
}

export default Growth;
